# Generated by Django 2.1.3 on 2019-02-14 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the experiment')),
                ('stimulus', models.CharField(default='N/A', max_length=200)),
                ('notes', models.CharField(default='N/A', max_length=1000)),
                ('path', models.CharField(default='N/A', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cricket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntrinsicImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='N/A', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the experiment')),
                ('region', models.CharField(default='V1', max_length=100)),
                ('stimulus', models.CharField(default='N/A', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_name', models.CharField(max_length=200)),
                ('dob', models.DateField(default=django.utils.timezone.localdate, verbose_name='date of birth')),
                ('mouse_strain', models.CharField(default='C57BL/6', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of operation')),
                ('type', models.CharField(default='Headbar/Craniotomy', max_length=100)),
                ('notes', models.CharField(default='N/A', max_length=5000)),
                ('anesthesia', models.CharField(default='FMM', max_length=100)),
                ('mouse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='loggers.Mouse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwoPhoton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the experiment')),
                ('stimulusPath', models.CharField(default='N/A', max_length=200)),
                ('scopePath', models.CharField(default='N/A', max_length=200)),
                ('auxPath', models.CharField(default='N/A', max_length=200)),
                ('mouse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_photon', to='loggers.Mouse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_photon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VRExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the experiment')),
                ('stimulus', models.CharField(default='N/A', max_length=200)),
                ('notes', models.CharField(default='N/A', max_length=1000)),
                ('fluorescencePath', models.CharField(default='N/A', max_length=200)),
                ('trackPath', models.CharField(default='N/A', max_length=200)),
                ('stimulusPath', models.CharField(default='N/A', max_length=200)),
                ('mouse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_experiment', to='loggers.Mouse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_experiment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date window was taken')),
                ('bfPath', models.CharField(default='N/A', max_length=1000)),
                ('flPath', models.CharField(default='N/A', max_length=1000)),
                ('other_path', models.CharField(default='N/A', max_length=1000)),
                ('region', models.CharField(default='V1', max_length=100)),
                ('mouse_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window', to='loggers.Mouse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intrinsicimaging',
            name='mouse_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrinsic_imaging', to='loggers.Mouse'),
        ),
        migrations.AddField(
            model_name='intrinsicimaging',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrinsic_imaging', to=settings.AUTH_USER_MODEL),
        ),
    ]
