# Generated by Django 2.1.3 on 2019-05-15 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the experiment')),
                ('stimulus', models.CharField(default='N/A', max_length=200)),
                ('notes', models.TextField(default='N/A', max_length=1000)),
                ('path', models.CharField(default='N/A', max_length=200)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cricket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentType',
            fields=[
                ('experiment_name', models.CharField(default='N/A', max_length=200, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='experiment_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImmunoStain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the experiment')),
                ('im_path', models.CharField(default='N/A', max_length=200)),
                ('other_path', models.CharField(default='N/A', max_length=200)),
                ('notes', models.TextField(default='N/A', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='IntrinsicImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='N/A', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the experiment')),
                ('region', models.CharField(default='V1', max_length=100)),
                ('stimulus', models.CharField(default='N/A', max_length=200)),
                ('experiment_type', models.ManyToManyField(related_name='intrinsicimaging_type', to='loggers.ExperimentType')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_name', models.CharField(default='N/A', max_length=200, primary_key=True, serialize=False)),
                ('license_id', models.CharField(default='N/A', max_length=200)),
                ('expiration_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date of expiration')),
                ('members', models.ManyToManyField(related_name='license_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='license', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('mouse_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('dob', models.DateField(default=django.utils.timezone.localdate, verbose_name='date of birth')),
                ('mouse_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='female', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MouseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MouseSet', to='loggers.License')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Mouseset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(default='N/A', max_length=200, primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(related_name='project_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of scoring')),
                ('carprofen', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=3, verbose_name='Carprofen')),
                ('weight', models.FloatField(default=0, verbose_name='Weight (g)')),
                ('food_consumed', models.FloatField(default=0, verbose_name='Food Consumed (g)')),
                ('behavior', models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2')], default='N/A', max_length=3)),
                ('posture_fur', models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2')], default='N/A', max_length=3)),
                ('water_food_uptake', models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2')], default='N/A', max_length=3)),
                ('general_condition', models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2')], default='N/A', max_length=3)),
                ('skin_turgor', models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2')], default='N/A', max_length=3)),
                ('slug', models.SlugField(unique=True)),
                ('brain_surgery', models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2')], default='N/A', max_length=3)),
                ('lid_suture', models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2')], default='N/A', max_length=3)),
                ('inutero_electroporation', models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2')], default='N/A', max_length=3)),
                ('notes', models.TextField(default='N/A', max_length=1000)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheet', to='loggers.Mouse')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='score_sheet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('strain_name', models.CharField(default='C57Bl6', max_length=200, primary_key=True, serialize=False)),
                ('ab_path', models.CharField(default='N/A', max_length=1000)),
                ('im_path', models.CharField(default='N/A', max_length=200)),
                ('license', models.ManyToManyField(related_name='strain', through='loggers.MouseSet', to='loggers.License')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='strain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of operation')),
                ('duration', models.IntegerField(default=1, verbose_name='Duration in minutes of the procedure')),
                ('notes', models.TextField(default='N/A', max_length=5000)),
                ('anesthesia', models.CharField(choices=[('FMM', 'FMM'), ('Iso', 'Isofluorane')], default='FMM', max_length=100)),
                ('experiment_type', models.ManyToManyField(related_name='surgery_type', to='loggers.ExperimentType')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='loggers.Mouse')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwoPhoton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the experiment')),
                ('stimulusPath', models.CharField(default='N/A', max_length=200)),
                ('scopePath', models.CharField(default='N/A', max_length=200)),
                ('auxPath', models.CharField(default='N/A', max_length=200)),
                ('experiment_type', models.ManyToManyField(related_name='twophoton_type', to='loggers.ExperimentType')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_photon', to='loggers.Mouse')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='two_photon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VRExperiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of the experiment')),
                ('stimulus', models.CharField(default='N/A', max_length=200)),
                ('fluorescencePath', models.CharField(default='N/A', max_length=200)),
                ('trackPath', models.CharField(default='N/A', max_length=200)),
                ('stimulusPath', models.CharField(default='N/A', max_length=200)),
                ('notes', models.TextField(default='N/A', max_length=5000)),
                ('experiment_type', models.ManyToManyField(related_name='vrexperiment_type', to='loggers.ExperimentType')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_experiment', to='loggers.Mouse')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vr_experiment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date window was taken')),
                ('bfPath', models.CharField(default='N/A', max_length=1000)),
                ('flPath', models.CharField(default='N/A', max_length=1000)),
                ('other_path', models.CharField(default='N/A', max_length=1000)),
                ('region', models.CharField(choices=[('V1', 'Primary visual cortex'), ('mPFC', 'medial Prefrontal Cortex'), ('HVAs', 'Higher Visual Areas'), ('S1', 'Primary somatosensory cortex'), ('A1', 'Primary auditory cortex'), ('S1V1', 'Primary visual and somatosensory cortex')], default='V1', max_length=100)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='window', to='loggers.Mouse')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='window', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mouseset',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MouseSet', to='loggers.Strain'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='mouse_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to='loggers.MouseSet'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouse',
            name='strain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse', to='loggers.Strain'),
        ),
        migrations.AddField(
            model_name='license',
            name='project',
            field=models.ManyToManyField(related_name='license', to='loggers.Project'),
        ),
        migrations.AddField(
            model_name='intrinsicimaging',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intrinsic_imaging', to='loggers.Mouse'),
        ),
        migrations.AddField(
            model_name='intrinsicimaging',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='intrinsic_imaging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immunostain',
            name='mouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immuno_stain', to='loggers.Mouse'),
        ),
        migrations.AddField(
            model_name='immunostain',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='immunostain', to=settings.AUTH_USER_MODEL),
        ),
    ]
