# Generated by Django 2.1.3 on 2019-07-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrinsicimaging',
            name='mapPath',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
