# Generated by Django 2.1.3 on 2019-07-02 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loggers', '0003_auto_20190702_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='strain_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='mouseset',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouseset', to='loggers.License'),
        ),
        migrations.AlterField(
            model_name='mouseset',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mouseset', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mouseset',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouseset', to='loggers.Strain'),
        ),
    ]
