# Generated by Django 2.1.3 on 2019-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loggers', '0004_auto_20190702_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='testPath',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
